name: Continous Integration
on: [push, pull_request]

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: extdn/github-actions-m2/magento-coding-standard@master

  phpmd:
    name: Magento 2 - Phpmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: extdn/github-actions-m2/magento-mess-detector@master

  integration:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    container:
      image: duhon/php:7.3-alpine

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: magento2
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: extdn/github-actions-m2/install-m2-from-mirror@master
        with:
          ce-version: 2.3.3
